[project]
name = "geo-forge"
version = "0.1.0"
description = "Gaussian Environment Optimization Forge"
readme = "README.md"
authors = [
    { name = "Masaya Kataoka", email = "ms.kataoka@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dataclasses>=0.8",
    "depth-anything-3",
    "nuscenes-devkit>=1.2.0",
    "opencv-python>=4.8.0",
    "pillow>=10.0.0",
    "python-dotenv>=1.0.0",
    "torch>=2.0.0",
    "transformers",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
depth-anything-3 = { git = "https://github.com/ByteDance-Seed/Depth-Anything-3.git" }
torch = [
  { index = "pytorch-cu124", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu124", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
transformers = { git = "https://github.com/huggingface/transformers.git", rev = "v5.0.0rc0" }
